name: Continuous Persistent VPS with Tailscale + sshx.io

on:
  workflow_dispatch:
  repository_dispatch:
    types: [start-vps]

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 359

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y curl unzip git sudo net-tools neofetch jq

      - name: Install Tailscale
        run: curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start Tailscale
        run: |
          sudo tailscaled &
          sleep 8
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname=biralo || echo "Tailscale already up"

      - name: Create user biralo with sudo
        run: |
          if ! id -u biralo >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash biralo
            echo "biralo:biralo" | sudo chpasswd
            sudo usermod -aG sudo biralo
            echo "biralo ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/biralo
          fi

      - name: Get Tailscale IPv4 address
        id: tailscale_ip
        run: |
          IP=$(tailscale ip -4 || echo "No IP found")
          echo "ip=$IP" >> $GITHUB_OUTPUT

      - name: Install sshx
        run: curl -sSf https://sshx.io/get | sh

      - name: Start sshx.io session & get link
        id: sshx_session
        run: |
          sshx > sshx.log 2>&1 &
          sleep 6
          LINK=$(grep -m1 -o "https://sshx.io/s/[^ ]*" sshx.log || echo "")
          echo "link=$LINK" >> $GITHUB_OUTPUT

      - name: Send Discord Webhook with VPS info
        run: |
          USER_ID="${{ github.event.client_payload.requester_id }}"
          USER_TAG="${{ github.event.client_payload.requester_tag }}"
          IP="${{ steps.tailscale_ip.outputs.ip }}"
          SSHLINK="${{ steps.sshx_session.outputs.link }}"
          PAYLOAD=$(jq -n \
            --arg ip "$IP" \
            --arg ssh "$SSHLINK" \
            --arg userid "$USER_ID" \
            --arg tag "$USER_TAG" \
            --arg username "biralo" \
            --arg password "biralo" \
            '{
              content: "<@\($userid)>",
              embeds: [{
                title: "🌐 VPS Info",
                color: 65280,
                fields: [
                  {name: "Requested by", value: $tag, inline: true},
                  {name: "Username", value: $username, inline: true},
                  {name: "Password", value: $password, inline: true},
                  {name: "Tailscale IPv4", value: $ip, inline: true},
                  {name: "🔑 SSHX Session", value: "[Open Web Terminal](\($ssh))", inline: false}
                ],
                footer: {text: "Powered by Zerioak"}
              }]
            }')
          curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" ${{ secrets.DISCORD_WEBHOOK }}

      - name: VPS alive (~5h 58m)
        run: sleep 21500

      - name: Trigger next VPS session before shutdown
        if: always()
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -d '{"event_type": "start-vps"}'            
      - name: VPS alive (~5h 58m)
        run: sleep 21500

      - name: Trigger next VPS session before shutdown
        if: always()
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -d '{"event_type": "start-vps"}'
